{application,cfclient,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{cfclient_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cfclient,cfclient_app,cfclient_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
